dev_essential: refactored fpack and funpack, add REQUIRED line to all essential cmds

diff --git a/shbin/fappend b/shbin/fappend
--- a/shbin/fappend
+++ b/shbin/fappend
@@ -3,41 +3,42 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  fappend
 #%   DESCRIPTION:  Append the content to the tail of the given file
-#%	 Usage: fappend 'file.name' 'new_content' OR echo 'new_content' | fappend 'file.name'
+#%   USAGE: fappend 'file.name' 'new_content' OR echo 'new_content' | fappend 'file.name'
+#%   REQUIRES: abspath, [bktohome], cat
 #----------------------------------------------------------------------------------------------------------------------
 _fappend() {
     if [ $# -lt 1 ];then
-	   echo "Usage: fappend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'" >&2
+       echo "Usage: fappend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'" >&2
        return 1
     else
        local fn="$(abspath "$1")"
     fi
     if [ ! -r "$fn" ];then
-	   echo "$fn is not a valid file or cannot be read!" >&2
-	   return 1
-	else
-	   shift
-	fi
-	bktohome "$fn"
+       echo "$fn is not a valid file or cannot be read!" >&2
+       return 1
+    else
+       shift
+    fi
+    [ -x "$(which bktohome)" ] && bktohome "$fn"
     ##echo "$@" >> "$fn"
-	if [ $# -lt 1 ];then
+    if [ $# -lt 1 ];then
     cat >> "$fn" <<EOF
 $(cat)
 EOF
-	else
+    else
     cat >> "$fn" <<EOF
 $@
 EOF
-	fi
+    fi
 }
 
 
 if [ $# -lt 1 ]; then
-	echo "Usage: fappend filename newcontent" >&2
+    echo "Usage: fappend filename newcontent" >&2
 elif [ $# -eq 1 ]; then
-	_fappend "$1" "$(cat)"
+    _fappend "$1" "$(cat)"
 else
-	_fappend "$@"
+    _fappend "$@"
 fi
 
 unset -f _fappend
diff --git a/shbin/finsert b/shbin/finsert
--- a/shbin/finsert
+++ b/shbin/finsert
@@ -3,11 +3,12 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  finsert
 #%   DESCRIPTION:  Insert the content before/after the pattern matched strings of the given file
-#%	 Usage:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"
+#%   USAGE:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"
+#%   REQUIRES: abspath, tr, sed, erow
 #----------------------------------------------------------------------------------------------------------------------
 __ScriptTmp="$(mktemp -d)"
 _finsert() {
-	if [ $# -lt 3 ]; then
+    if [ $# -lt 3 ]; then
         echo 'Usage:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"' >&2
         return 1
     fi;
@@ -23,29 +24,29 @@ _finsert() {
             fi
             shift
             case "$1" in
-				-a | --after)
-					fpos='after'
-					shift
-					;;
-				-b | --before)
-					fpos='before'
-					shift
-					;;
-				-- | *)
-					;;
-			esac
+                -a | --after)
+                    fpos='after'
+                    shift
+                    ;;
+                -b | --before)
+                    fpos='before'
+                    shift
+                    ;;
+                -- | *)
+                    ;;
+            esac
         ;;
-		-a | --after)
-				fpos='after'
-				shift
-				;;
-		-b | --before)
-				fpos='before'
-				shift
-				;;
-		-- | *)
-				;;
-	esac
+        -a | --after)
+                fpos='after'
+                shift
+                ;;
+        -b | --before)
+                fpos='before'
+                shift
+                ;;
+        -- | *)
+                ;;
+    esac
     local fn="$(abspath "$1")"
     if [ ! -r "$fn" ]; then
         echo "$fn is not a valid file or cannot be read!" 1>&2
@@ -53,39 +54,39 @@ _finsert() {
     else
         shift
     fi
-	local pat="$(echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g')"
-	shift
-	local txt="$(echo "$@" | sed -e 's/[\/&]/\\&/g')"
-	local suf="bk$(date +%s)"
-	local nst=""
-	nst="$(sed -n -e "/${pat}/=" "$fn" 2>/dev/null)"
-	if [ -z "$nst" ]; then
-		echo "Cannot find the lines containing the $pat in $fn" >&2
-		return 1
-	fi
-	local ntl=""
-	ntl="$(erow "$nth" "$nst")"
+    local pat="$(echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g')"
+    shift
+    local txt="$(echo "$@" | sed -e 's/[\/&]/\\&/g')"
+    local suf="bk$(date +%s)"
+    local nst=""
+    nst="$(sed -n -e "/${pat}/=" "$fn" 2>/dev/null)"
+    if [ -z "$nst" ]; then
+        echo "Cannot find the lines containing the $pat in $fn" >&2
+        return 1
+    fi
+    local ntl=""
+    ntl="$(erow "$nth" "$nst")"
     if [ -z "$ntl" ]; then
-		echo "Cannot get the number of the #$nth matching line containing $pat in $fn" >&2
-		return 1
-	else
-		echo "Insert [$txt] $fpos [$pat] in the #${ntl} line of $fn."
-	fi
-	case "$fpos" in
-		before)
-			sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/${txt}\n\1/" "$fn"
-			;;
-		*)
-			sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/\1\n${txt}/" "$fn"
-			;;
-	esac
+        echo "Cannot get the number of the #$nth matching line containing $pat in $fn" >&2
+        return 1
+    else
+        echo "Insert [$txt] $fpos [$pat] in the #${ntl} line of $fn."
+    fi
+    case "$fpos" in
+        before)
+            sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/${txt}\n\1/" "$fn"
+            ;;
+        *)
+            sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/\1\n${txt}/" "$fn"
+            ;;
+    esac
 }
 
 
 if [ $# -lt 1 ]; then
-	echo 'Usage:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"' >&2
+    echo 'Usage:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"' >&2
 else
-	_finsert "$@"
+    _finsert "$@"
 fi
 
 unset -f _finsert
diff --git a/shbin/fprepend b/shbin/fprepend
--- a/shbin/fprepend
+++ b/shbin/fprepend
@@ -1,47 +1,47 @@
 
-## require shbin/abspath
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  fprepend
+#    NAME:  fprepend
 #%   DESCRIPTION: Prepend the content to the tail of the given file
-#%	 Usage: fprepend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'
+#%   USAGE: fprepend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'
+#%   REQUIRES: abspath, date, cat, mv, [bktohome]
 #----------------------------------------------------------------------------------------------------------------------
 __ScriptTmp="$(mktemp -d)"
 _fprepend() {
     if [ $# -lt 1 ];then
-	   echo "Usage: fprepend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'" >&2
+       echo "Usage: fprepend 'file.name' 'new_content' OR echo 'new_content' | fprepend 'file.name'" >&2
        return 1
     else
        local fn="$(abspath "$1")"
     fi
     if [ ! -r "$fn" ];then
-	   echo "$fn is not a valid file or cannot be read!" >&2
-	   return 1
-	else
-	   shift
-	fi
-	local tmpfn="tpf$(date +%s)"
-	bktohome "$fn"
+       echo "$fn is not a valid file or cannot be read!" >&2
+       return 1
+    else
+       shift
+    fi
+    local tmpfn="tpf$(date +%s)"
+    [ -x $(which bktohome) ] && bktohome "$fn"
     ##echo "$@" | cat - "$fn" > "$__ScriptTmp/$tmpfn" && \mv -f "$__ScriptTmp/$tmpfn" "$fn"
-	if [ $# -lt 1 ];then
+    if [ $# -lt 1 ];then
     cat > "$__ScriptTmp/$tmpfn" <<EOF
 $(cat)
 EOF
-	else
+    else
     cat > "$__ScriptTmp/$tmpfn" <<EOF
 $@
 EOF
-	fi
+    fi
     cat "$fn" >> "$__ScriptTmp/$tmpfn"
     \mv -f "$__ScriptTmp/$tmpfn" "$fn"
 }
 
 
 if [ $# -lt 1 ]; then
-	echo "Usage: fprepend filename newcontent" >&2
+    echo "Usage: fprepend filename newcontent" >&2
 elif [ $# -eq 1 ]; then
-	_fprepend "$1" "$(cat)"
+    _fprepend "$1" "$(cat)"
 else
-	_fprepend "$@"
+    _fprepend "$@"
 fi
 
 unset -f _fprepend
diff --git a/shbin/fsplit b/shbin/fsplit
--- a/shbin/fsplit
+++ b/shbin/fsplit
@@ -1,12 +1,12 @@
 
-## require shbin/abspath, shbin/escape
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
-#          NAME:  fsplit
-#%  DESCRIPTION:  Split the given file according to the given pattern
-#%	Usage: fsplit [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*"
+#    NAME:  fsplit
+#%   DESCRIPTION:  Split the given file according to the given pattern
+#%   USAGE: fsplit [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*"
+#%   REQUIRES: abspath, escape, tr, ecalc, basename, sed, date, erow, nrows, head, tail
 #----------------------------------------------------------------------------------------------------------------------
 _fsplit() {
-	if [ $# -lt 1 ]; then
+    if [ $# -lt 1 ]; then
         echo 'Usage:fsplit [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*"' >&2
         return 1
     fi;
@@ -22,76 +22,71 @@ _fsplit() {
             fi
             shift
             case "$1" in
-				-a | --after)
-					fpos=1024
-					shift
+                -a | --after)
+                    fpos=1024
+                    shift
                 ;;
                 -b | --before)
-					fpos=0
-					shift
-				;;
-				-- | *)
-				;;
-			esac
+                    fpos=0
+                    shift
+                ;;
+                -- | *)
+                ;;
+            esac
         ;;
-		-a | --after)
-				fpos=1024
-				shift
-				;;
-		-b | --before)
-				fpos=0
-				shift
-				;;
-		-- | *)
-				;;
-	esac
+        -a | --after)
+                fpos=1024
+                shift
+                ;;
+        -b | --before)
+                fpos=0
+                shift
+                ;;
+        -- | *)
+                ;;
+    esac
     local fn="$(abspath "$1")"
     if [ ! -r "$fn" ]; then
         echo "$fn is not a valid file or cannot be read!" 1>&2
         return 1
     else
         shift
-		local suf="bk$(date +%s)"
-		\cp -f "$fn" "$fn.$suf"
-		local fb="$(basename $fn)"
+        local suf="bk$(date +%s)"
+        \cp -f "$fn" "$fn.$suf"
+        local fb="$(basename $fn)"
     fi
-	if [ $# -lt 1 ]; then
-		local pat="$(cat)"
-	else
-		local pat="$*"
-	fi
-	pat="$(echo "$pat" | sed -e 's/[]\/$*.^|[]/\\&/g')"
+    if [ $# -lt 1 ]; then
+        local pat="$(cat)"
+    else
+        local pat="$*"
+    fi
+    pat="$(echo "$pat" | sed -e 's/[]\/$*.^|[]/\\&/g')"
     nst="$(sed -n -e "/${pat}/=" "$fn" 2>/dev/null)"
     local n1t="$(erow 1 "$nst")"
     local nmt="$(erow $nth "$nst")"
     if [ -z "$nmt" ] || [ "$nmt" -lt 1 ]; then
-		echo "Cannot find the #$nth $pat in $fn" >&2
-		return 1
-	fi
-	local floc="after"
-	if [ "$fpos" -lt 512 ]; then
-		nmt="$((nmt-1))"
-		floc="before"
-	fi
-	local nrtot="$(cat $fn | nrows)"
-	local nlf="$(ecalc "$nrtot-$nmt")"
-	if [ "$nmt" -lt "$nrtot" ];then
-	   echo "Splitting $fn into $fb.part1 and $fb.part2 $floc #$num [$pat] matching line #$nmt"
-			head -n "$nmt" "$fn" > "$fb.part1"
-			tail -n "$nlf" "$fn" > "$fb.part2"
-			return 0
+        echo "Cannot find the #$nth $pat in $fn" >&2
+        return 1
+    fi
+    local floc="after"
+    if [ "$fpos" -lt 512 ]; then
+        nmt="$((nmt-1))"
+        floc="before"
+    fi
+    local nrtot="$(cat $fn | nrows)"
+    local nlf="$(ecalc "$nrtot-$nmt")"
+    if [ "$nmt" -lt "$nrtot" ];then
+       echo "Splitting $fn into $fb.part1 and $fb.part2 $floc #$num [$pat] matching line #$nmt"
+            head -n "$nmt" "$fn" > "$fb.part1"
+            tail -n "$nlf" "$fn" > "$fb.part2"
+            return 0
     else
        echo "File split operation failed!" >&2
        return 1
     fi
 }
 
-
-if [ $# -lt 1 ]; then
-	echo 'Usage:fsplit [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*"' >&2
-else
-	_fsplit "$@"
-fi
+_fsplit "$@"
 
 unset -f _fsplit
 exit 0
diff --git a/shbin/fsubst b/shbin/fsubst
--- a/shbin/fsubst
+++ b/shbin/fsubst
@@ -1,58 +1,55 @@
 
-##require shbin/abspath, shbin/escape
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  fsubst
 #%   DESCRIPTION:  Substitute all matched string with new string in the given file
-#%	 Usage: fsubst [-l] '/etc/default/grub' 'GRUB_CMDLINE_LINUX=' 'GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"'
+#%   USAGE: fsubst [-l] '/etc/default/grub' 'GRUB_CMDLINE_LINUX=' 'GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"'
+#%   REQUIRES: abspath, escape, sed
 #----------------------------------------------------------------------------------------------------------------------
 _fsubst() {
     if [ $# -lt 3 ];then
-	   echo 'Usage:  fsubst [-l] "$WP_CONFIG_FILE" ".*SALT_BLOCK.*" "$Alternative_Text"'
+       echo 'Usage:  fsubst [-l] "$WP_CONFIG_FILE" ".*SALT_BLOCK.*" "$Alternative_Text"'
        return 1
     fi
     local line=0
     case "$1" in
-		-l | --line | --change | --replace)
-			local line=1024
-			shift
-			;;
-		-- | *)
-			;;
-	esac
-	local fn="$(abspath "$1")"
+        -l | --line | --change | --replace)
+            local line=1024
+            shift
+            ;;
+        -- | *)
+            ;;
+    esac
+    local fn="$(abspath "$1")"
     if [ ! -r "$fn" ];then
-	   echo "$fn is not a valid file or cannot be read!" >&2
-	   return 1
-	else
-	   shift
-	fi
+       echo "$fn is not a valid file or cannot be read!" >&2
+       return 1
+    else
+       shift
+    fi
     ## Wrong: local pat=$(escape "$1")
-	local pat="$(echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g')"
-	shift
-	## Wrong: local txt=$(escape "$2")
-	##local txt="$(escape "$2")"
-	local txt="$(echo "$@" | sed -e 's/[\/&]/\\&/g')"
-	local suf="bk$(date +%s)"
-	if [ "$line" -lt 512 ]; then
-		echo "Replacing all [$pat] with [$txt] in $fn ..."
-		##$sh_c "sed -i.${suf} s/${pat}/${txt}/${num} ${fn}"
-		##sudo sed -i."$suf" "s/${pat}/${txt}/${num}" "$fn"
-		## prevent unwanted damage by not using sudo, chmod $fn explicitly
-		sed -i."$suf" "s/${pat}/${txt}/g" "$fn"
-	else
-		echo "Replacing all lines containing the [$pat] with [$txt] in $fn ..."
-		## http://stackoverflow.com/questions/18342674/sed-replace-a-line-containing-a-pattern
-		##$sh_c "sed -i.${suf} s/^.*${pat}.*$/${txt}/${num} ${fn}"
-		##sudo sed -i."$suf" "s/^.*${pat}.*$/${txt}/${num}" "$fn"
-		sed -i."$suf" "s/^.*${pat}.*$/${txt}/g" "$fn"
-	fi
+    local pat="$(echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g')"
+    shift
+    ## Wrong: local txt=$(escape "$2")
+    ##local txt="$(escape "$2")"
+    local txt="$(echo "$@" | sed -e 's/[\/&]/\\&/g')"
+    local suf="bk$(date +%s)"
+    if [ "$line" -lt 512 ]; then
+        echo "Replacing all [$pat] with [$txt] in $fn ..."
+        ##$sh_c "sed -i.${suf} s/${pat}/${txt}/${num} ${fn}"
+        ##sudo sed -i."$suf" "s/${pat}/${txt}/${num}" "$fn"
+        ## prevent unwanted damage by not using sudo, chmod $fn explicitly
+        sed -i."$suf" "s/${pat}/${txt}/g" "$fn"
+    else
+        echo "Replacing all lines containing the [$pat] with [$txt] in $fn ..."
+        ## http://stackoverflow.com/questions/18342674/sed-replace-a-line-containing-a-pattern
+        ##$sh_c "sed -i.${suf} s/^.*${pat}.*$/${txt}/${num} ${fn}"
+        ##sudo sed -i."$suf" "s/^.*${pat}.*$/${txt}/${num}" "$fn"
+        sed -i."$suf" "s/^.*${pat}.*$/${txt}/g" "$fn"
+    fi
 }
 
 
-if [ $# -lt 1 ]; then
-	echo "Usage: fsubst [-l] '/etc/default/grub' 'GRUB_CMDLINE_LINUX=' 'GRUB_CMDLINE_LINUX=\"cgroup_enable=memory swapaccount=1\"'" >&2
-else
-	_fsubst "$@"
-fi
+_fsubst "$@"
 
+unset -f _fsubst
 exit 0
diff --git a/shbin/funpack b/shbin/funpack
--- a/shbin/funpack
+++ b/shbin/funpack
@@ -1,15 +1,16 @@
 
-## require shbin/abspath
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  funpack & fpack
 #%   DESCRIPTION:  Quick uncompressing of archived packs
-#%   Usage: funpack [ -p | --path /target/path ] pack1.zip pack2.tar.gz pack3.tar ... packn.7z
+#%   USAGE: funpack [ -p | --path /target/path ] pack1.zip pack2.tar.gz pack3.tar ... packn.7z
+#%   REQUIRES: abspath, psbpath, basename, dirname, mktemp, pushd, popd, tar, [unlzma], [bunzip2], [unrar], [gunzip], [unzip], [uncompress], [7z], [unxz], [ar], [rpm2cpio], [cabextract]
 #----------------------------------------------------------------------------------------------------------------------
 _funpack() {
   if [ $# -lt 1 ] ; then
      echo "Usage: funpack [ -p | --path /target/path ] testpack.zip anotherpack.tar.gz"
      return 0
   fi
+  local targetpath=""
   case "$1" in
     -p | --path)
         shift
@@ -17,46 +18,57 @@ _funpack() {
         shift
     ;;
     -- | *)
-    ;
+        local targetpath="$(psbpath "$1")"
+        shift
+    ;;
   esac
+  [ -z "${targetpath}" ] && targetpath="$(pwd)"
+  if [ -e "${targetpath}" ] && [ -f "${targetpath}" ]; then
+    echo "Opt1 Invalid: Target path should be a directory, NOT a file!" >&2
+    exit 1
+  elif [ ! -e "${targetpath}" ] && [ -d "$(dirname ${targetpath})" ]; then
+    mkdir -p "${targetpath}" || echo "Opt1 Error: Target dir ${targetpath} can NOT be created!" && exit 1
+  fi
   if [ $# -gt 1 ] ; then
      local display_divider=1
   else
      local display_divider=0
   fi
-  local curopt=0
-  local numtotarg=$#
-  while [ ${curopt} -lt ${numtotarg} ]; do
-    local unpackpath="${targetpath}/$(urifilename "$1")"
-    [ ! -d "${targetpath}" ] && echo "${targetpath} is NOT a valid target directory" >&2 && exit 1
-    local current_pack="$(abspath "$1")"
+  local curarg=""
+  local leftargs="$@"
+  for curarg in ${leftargs}; do
+    local current_pack="$(abspath "$curarg")"
     if [ -n "$current_pack" ] && [ -f "$current_pack" ]; then
-        shift
+        local unpackpath="${targetpath}"
     else
-        echo "$1 is not a valid file path, skipping ..."
+        echo "$current_pack is not a valid file path, skipping ..."
         continue
     fi
 
     if [ "${display_divider}" -gt 0 ]; then
       echo "----------------------------------------"
-      echo "Unpacking ${current_pack} to current dir:"
+      echo "Unpacking ${current_pack} to ${unpackpath}:"
       echo "----------------------------------------"
     fi
     case $current_pack in
-       *.tar.bz2)   tar -C "${unpackpath}" xvjf "$current_pack" ;;
-       *.tar.gz)    tar -C "${unpackpath}" xvzf "$current_pack" ;;
-       *.tar.xz)    tar -C "${unpackpath}" xvzf "$current_pack" ;;
-       *.lzma)      unlzma -cd "$current_pack" > "${unpackpath}"    ;;
+       *.tar.bz2 | *.tbz2)   tar -C "${unpackpath}" -xvjf "$current_pack" ;;
+       *.tar.gz | *.tgz)    tar -C "${unpackpath}" -xvzf "$current_pack" ;;
+       *.tar.xz | *.txz)    tar -C "${unpackpath}" -xvJf "$current_pack" ;;
+       *.tar.7z | *.t7z)
+            local tmpdir="$(mktemp -d)"
+            local tmptar="$(echo $(basename ${current_pack}) | sed -e 's/\.tar\.7z//g;s/\.t7z//g').tar"
+            pushd "${tmpdir}" >/dev/null && 7z x -y "$current_pack" 2>/dev/null && tar -C "${unpackpath}" -xvf "$tmptar" && popd >/dev/null
+            rm -rf "${tmpdir}"
+        ;;
+       *.tar)       tar -C "${unpackpath}" -xvf "$current_pack"     ;;
        *.bz2)       bunzip2 -cd "$current_pack" > "${unpackpath}"   ;;
-       *.rar)       unrar x "$current_pack" "${unpackpath}"    ;;
        *.gz)        gunzip -rc "$current_pack" > "${unpackpath}";;
-       *.tar)       tar -C "${unpackpath}" xvf "$current_pack"     ;;
-       *.tbz2)      tar -C "${unpackpath}" xvjf "$current_pack"    ;;
-       *.tgz)       tar -C "${unpackpath}" xvzf "$current_pack"    ;;
+       *.xz)        unxz -cd "$current_pack" > "${unpackpath}"  ;;
+       *.7z)        pushd "${unpackpath}" >/dev/null && 7z x -y "$current_pack" 2>/dev/null && popd >/dev/null;;
+       *.rar)       unrar x -y "$current_pack" "${unpackpath}"    ;;
        *.zip)       unzip "$current_pack" -d "${unpackpath}"   ;;
        *.Z)         uncompress -rc "$current_pack" > "${unpackpath}"  ;;
-       *.7z)        7z x "$current_pack" -o "${unpackpath}"     ;;
-       *.xz)        unxz -cd "$current_pack" > "${unpackpath}"  ;;
+       *.lzma)      unlzma -cd "$current_pack" > "${unpackpath}"    ;;
        *.deb)       ar p "$current_pack" data.tar.gz | tar -C "${unpackpath}" xvzf -   ;;
        *.rpm)       rpm2cpio "$current_pack" | cpio -vi -d "${unpackpath}"  ;;
        *.exe)       cabextract "$current_pack" -d "${unpackpath}"  ;;
diff --git a/shbin/getpnamebyid b/shbin/getpnamebyid
--- a/shbin/getpnamebyid
+++ b/shbin/getpnamebyid
@@ -2,26 +2,27 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  getpname
 #%   DESCRIPTION:  Get the process name of the given pid
-#%   Usage: getpnamebyid process_id | process_path
+#%   USAGE: getpnamebyid process_id | process_path
+#%   REQUIRES: tr, ps
 #----------------------------------------------------------------------------------------------------------------------
 _getpname() {
-	if [ $# -ne 1 ]; then
-		echo "Usage: getpnamebyid process_id | process_path" >&2
-		return 1 
-	elif isdigit "$1" 2>/dev/null; then
-		local pid=$(echo "$1" | tr -cd '[[:digit:]]') 
-	else
-		echo "Invalid format of process id. getpnamebyid only accept digits." >&2
-		return 1 
-	fi
-	
-	pname="$(ps -p $pid -o comm= 2>/dev/null)"
-	if [ -z "$pname" ]; then
-		echo "Cannot find any running process with id $1" >&2 
-		return 1 
-	else
-		echo "$pname" 
-	fi
+    if [ $# -ne 1 ]; then
+        echo "Usage: getpnamebyid process_id | process_path" >&2
+        return 1
+    elif isdigit "$1" 2>/dev/null; then
+        local pid=$(echo "$1" | tr -cd '[[:digit:]]')
+    else
+        echo "Invalid format of process id. getpnamebyid only accept digits." >&2
+        return 1
+    fi
+
+    pname="$(ps -p $pid -o comm= 2>/dev/null)"
+    if [ -z "$pname" ]; then
+        echo "Cannot find any running process with id $1" >&2
+        return 1
+    else
+        echo "$pname"
+    fi
 }
 
 
diff --git a/shbin/getpos b/shbin/getpos
--- a/shbin/getpos
+++ b/shbin/getpos
@@ -3,40 +3,41 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  getpos
 #%   DESCRIPTION:  Get the given position from the file
-#%	 Usage: getpos rownum colnum filepath
+#%   USAGE: getpos rownum colnum filepath
+#%   REQUIRES: abspath, tr, getcol, erow
 #----------------------------------------------------------------------------------------------------------------------
 _getpos() {
     if [ $# -ne 3 ];then
-	   echo "Usage: getpos rownum colnum filename" >&2
-	   return 1
-	else
+       echo "Usage: getpos rownum colnum filename" >&2
+       return 1
+    else
        local nrow="$(echo $1 | tr -cd '[:digit:]')"
        local ncol="$(echo $2 | tr -cd '[:digit:]')"
        local fn="$(abspath "$3")"
     fi
-	if [ -z "$nrow" ];then
-	   echo "$nrow is not a valid row number!" >&2
-	   return 1
-	fi
+    if [ -z "$nrow" ];then
+       echo "$nrow is not a valid row number!" >&2
+       return 1
+    fi
     if [ -z "$ncol" ];then
        echo "$ncol is not a valid column number!" >&2
-	   return 1
+       return 1
     fi
     if [ ! -r "$fn" ];then
-	   echo "$fn is not a valid file or cannot be read!" >&2
-	   return 2
-	fi
+       echo "$fn is not a valid file or cannot be read!" >&2
+       return 2
+    fi
     getcol "$ncol" "$fn" | erow "$nrow"
 }
 
 
 if [ $# -lt 1 ]; then
-	echo "Usage: getpos rownum colnum filename" >&2
+    echo "Usage: getpos rownum colnum filename" >&2
 elif [ $# -eq 2 ]; then
-	_getpos "$1" "$2" "$(cat)"
+    _getpos "$1" "$2" "$(cat)"
 else
-	_getpos "$@"
-fi	
+    _getpos "$@"
+fi
 
 unset -f _getpos
 exit 0
diff --git a/shbin/getrow b/shbin/getrow
--- a/shbin/getrow
+++ b/shbin/getrow
@@ -1,38 +1,38 @@
 
-## require shbin/abspath, shbin/erow
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  getrow
 #%   DESCRIPTION:  Get the given row from the file
-#%   Usage: getrow rownum filepath
+#%   USAGE: getrow rownum filepath
+#%   REQUIRES: tr, abspath, erow
 #----------------------------------------------------------------------------------------------------------------------
 _getrow() {
     if [ $# -ne 2 ];then
-	   echo "Usage: getrow rownum filename" >&2
-	   return 1
-	else
-       local nrow="$(echo $1 | tr -cd '[:digit:]')"
+       echo "Usage: getrow rownum filename" >&2
+       return 1
+    else
+       local nrow="$(echo "$1" | tr -cd '[:digit:]')"
        local fn="$(abspath "$2")"
     fi
 
-	if [ -z "$nrow" ];then
-	   echo "$nrow is not a valid row number!" >&2
-	   return 1
-	fi
+    if [ -z "$nrow" ];then
+       echo "$nrow is not a valid row number!" >&2
+       return 1
+    fi
     if [ ! -r "$fn" ];then
-	   echo "$fn is not a valid file or cannot be read!" >&2
-	   return 2
-	fi
-	cat "$fn" | erow "$nrow"
+       echo "$fn is not a valid file or cannot be read!" >&2
+       return 2
+    fi
+    cat "$fn" | erow "$nrow"
 }
 
 
 if [ $# -lt 1 ]; then
-	echo "Usage: getrow rownum filename" >&2
+    echo "Usage: getrow rownum filename" >&2
 elif [ $# -eq 1 ]; then
-	_getrow "$1" "$(cat)"
+    _getrow "$1" "$(cat)"
 else
-	_getrow "$@"
-fi	
+    _getrow "$@"
+fi
 
 unset -f _getrow
 exit 0
diff --git a/shbin/getsshport b/shbin/getsshport
--- a/shbin/getsshport
+++ b/shbin/getsshport
@@ -3,25 +3,26 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  getsshport
 #%   DESCRIPTION:  output the SSHD listening port
-#%	 Usage: getsshport
+#%   USAGE: getsshport
+#%   REQUIRES: /etc/ssh/sshd_config, grep, tr
 #----------------------------------------------------------------------------------------------------------------------
 _getsshport() {
-	if [ -f "/etc/ssh/sshd_config" ]; then
-		local sshport="$(cat /etc/ssh/sshd_config | grep Port | tr -cd '[[:digit:]]')"
-		if [ -z "$sshport" ]; then
-			echo "Failed to grep Port number in /etc/ssh/sshd_config" >&2
-			return 1
-		else
-			echo "$sshport"
-			return 0
-		fi
-	else
-		echo "Cannot find /etc/ssh/sshd_config" >&2
-		return 1
-	fi
+    if [ -f "/etc/ssh/sshd_config" ]; then
+        local sshport="$(cat /etc/ssh/sshd_config | grep Port | tr -cd '[[:digit:]]')"
+        if [ -z "$sshport" ]; then
+            echo "Failed to grep Port number in /etc/ssh/sshd_config" >&2
+            return 1
+        else
+            echo "$sshport"
+            return 0
+        fi
+    else
+        echo "Cannot find /etc/ssh/sshd_config" >&2
+        return 1
+    fi
 }
 
-_getsshport 
+_getsshport
 
-unset -f _getsshport 
+unset -f _getsshport
 exit 0
diff --git a/shbin/hiver b/shbin/hiver
--- a/shbin/hiver
+++ b/shbin/hiver
@@ -2,10 +2,11 @@
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  vernum_recmp
 #%   DESCRIPTION:  Version number reursive comparing, only . symbol allowed
-#%	 Usage: hiver 3.08.1 3.13.1
+#%   USAGE: hiver 3.08.1 3.13.1 => 3.13.1, hiver 3.5.1 3.4.15 => 3.5.1
+#%   REQUIRES: cut, printf, sort, tail
 #----------------------------------------------------------------------------------------------------------------------
 _vernum_recmp() {
-   	[ "$1" = "$2" ] && return 10
+    [ "$1" = "$2" ] && return 10
 
    local v1f=$(echo "$1" | cut -d '.' -f -1)
    local v1b=$(echo "$1" | cut -d '.' -f 2-)
@@ -28,24 +29,24 @@ _vernum_recmp() {
 
 
 if [ $# -lt 2 ]; then
-	echo "Usage: hiver 12.0.04 12.1.01" >&2 
+    echo "Usage: hiver 12.0.04 12.1.01" >&2
 else
-	kv1="$1" 
-	kv2="$2" 
+    kv1="$1"
+    kv2="$2"
 fi
 
 if [ -n "$(echo "${kv1}${kv2}" | efilter -a)" ]; then
-	printf "${kv1}\n${kv2}" | sort -t'.' -V 2>/dev/null | tail -1
+    printf "${kv1}\n${kv2}" | sort -t'.' -V 2>/dev/null | tail -1
 else
-	_vernum_recmp "$kv1" "$kv2" 
-	case "$?" in
-		10 | 11)
-			echo "$kv1";;
-		9)
-			echo "$kv2";;
-		*)
-			echo "Error: failed to compare $kv1 $kv2" >&2;;
-	esac
+    _vernum_recmp "$kv1" "$kv2"
+    case "$?" in
+        10 | 11)
+            echo "$kv1";;
+        9)
+            echo "$kv2";;
+        *)
+            echo "Error: failed to compare $kv1 $kv2" >&2;;
+    esac
 fi
 
 exit 0
diff --git a/shbin/suba b/shbin/suba
--- a/shbin/suba
+++ b/shbin/suba
@@ -1,20 +1,20 @@
 
 #%   DESCRIPTION:  Super bash shell [ sudo bash -c for bash called scriptfile/bash console ]
-#%	 Usage: 	suba 'echo "Current shell is $SHELL"' OR suba "echo 'Current shell is $SHELL'"
-#%	 			OR suba bashcmd | bashfile
-
+#%   USAGE:     suba 'echo "Current shell is $SHELL"' OR suba "echo 'Current shell is $SHELL'"
+#%              OR suba bashcmd | bashfile
+#%   REQUIRES: shuser, sudo, su
 ##----------------------------------------------------  Super BASH Shell ------------------------------------------------
 suba='bash -c'
 if [ "$(shuser)" != 'root' ]; then
-	if iscommand "sudo" 2>/dev/null; then
-		suba='sudo bash -c'
-	elif iscommand "su" 2>/dev/null; then
-		suba='su -c'
-	else
-		echo >&2 'Error: this script needs the priviledge to run commands as root.'
-		echo >&2 'We are unable to find either "sudo" or "su" available to make this happen.'
-		exit 1
-	fi
+    if iscommand "sudo" 2>/dev/null; then
+        suba='sudo bash -c'
+    elif iscommand "su" 2>/dev/null; then
+        suba='su -c'
+    else
+        echo >&2 'Error: this script needs the priviledge to run commands as root.'
+        echo >&2 'We are unable to find either "sudo" or "su" available to make this happen.'
+        exit 1
+    fi
 fi
 
-$suba "$@" 
+$suba "$@"
