dev_essential: fix nrows 0 line issue and update finsert, fsplit funcs

diff --git a/shbin/finsert b/shbin/finsert
--- a/shbin/finsert
+++ b/shbin/finsert
@@ -11,32 +11,36 @@ _finsert() {
         echo 'Usage:finsert [ -n|--nth 3 ] [-a|-b|--after|--before] "$WP_CONFIG_FILE" ".*Matching_Pattern.*" "$ANY_TEXT_TO_INSERT"' >&2
         return 1
     fi;
-    local fpos='-a'
-    local num=1
+    local fpos='after'
+    local nth=1
     case "$1" in
         -n | --nth | --num | --number)
             shift
-            local num="$(echo "$1" | tr -cd '[:digit:]')"
-            if [ -z "$num" ]; then
+            local nth="$(echo "$1" | tr -cd '[:digit:]')"
+            if [ -z "$nth" ]; then
                 echo "A non-digit value is given to -n option."
                 return 1
             fi
             shift
-            if [ "-a" == "$1" ] || [ "--after" == "$1" ]; then
-                fpos='-a'
-                shift
-            fi
-            if [ "-b" == "$1" ] || [ "--before" == "$1" ]; then
-                fpos='-b'
-                shift
-            fi
+            case "$1" in
+				-a | --after)
+					fpos='after'
+					shift
+					;;
+				-b | --before)
+					fpos='before'
+					shift
+					;;
+				-- | *)
+					;;
+			esac
         ;;
 		-a | --after)
-				fpos='-a'
+				fpos='after'
 				shift
 				;;
 		-b | --before)
-				fpos='-b'
+				fpos='before'
 				shift
 				;;
 		-- | *)
@@ -49,16 +53,32 @@ _finsert() {
     else
         shift
     fi
-	local pat="$(escape $1)"
+	local pat="$(echo "$1" | sed -e 's/[]\/$*.^|[]/\\&/g')"
 	shift
-	local txt="$*"
-	fsplit -n "$num" "$fpos" "$fn" "$pat"
-	if [ $? -eq 0 ]; then
-		echo "$txt" | fappend "${fn}.part1"
-		cat "${fn}.part1" "${fn}.part2" > "$fn"
-		\mv -f "${fn}.part1" "$__ScriptTmp/" 2>/dev/null
-		\mv -f "${fn}.part2" "$__ScriptTmp/" 2>/dev/null
+	local txt="$(echo "$@" | sed -e 's/[\/&]/\\&/g')"
+	local suf="bk$(date +%s)"
+	local nst=""
+	nst="$(sed -n -e "/${pat}/=" "$fn" 2>/dev/null)"
+	if [ -z "$nst" ]; then
+		echo "Cannot find the lines containing the $pat in $fn" >&2
+		return 1
 	fi
+	local ntl=""
+	ntl="$(erow "$nth" "$nst")"
+    if [ -z "$ntl" ]; then
+		echo "Cannot get the number of the #$nth matching line containing $pat in $fn" >&2
+		return 1
+	else
+		echo "Insert [$txt] $fpos [$pat] in the #${ntl} line of $fn."
+	fi
+	case "$fpos" in
+		before)
+			sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/${txt}\n\1/" "$fn"
+			;;
+		*)
+			sed -i."$suf" "$ntl,${ntl}s/\(^.*${pat}.*$\)/\1\n${txt}/" "$fn"
+			;;
+	esac
 }
 
 
