dev_advanced: shbin extra tools v1.0 rel 2015.03.15

diff --git a/shbin/ncurl b/shbin/ncurl
--- a/shbin/ncurl
+++ b/shbin/ncurl
@@ -1,9 +1,8 @@
 
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #         NAME:  mcurl
-#%   DESCRIPTION:  Multipart curl function
-#%   USAGE: ncurl [-n|--npart 5 --option '--digest'] proto://user:pass@sub.domain.com:port/path/file.ext [local_filename]
-#%   REQUIRES: curl, getpid, waiton, uriproto, uriaccount, urifilename, urifileext, urifile, urihost, psbpath, sed, awk, ecalc
+#%  DESCRIPTION:  Multipart curl function
+#%	Usage: ncurl [-n|--npart 5 --option '--digest'] proto://user:pass@sub.domain.com:port/path/file.ext [local_filename]
 #----------------------------------------------------------------------------------------------------------------------
 _mcurl() {
    if ! iscommand curl 2>/dev/null;then
@@ -65,63 +64,63 @@ _mcurl() {
       echo "File $dstfn, Size $fsize, Downloading ... ..." >&2
       if [ -n "$facc" ]; then
          echo "curl $curlopt --digest --user $facc $furl -o $fdst" >&2
-         curl "$curlopt" --digest --user "$facc" "$furl" -o "$fdst"
-      else
+	     curl "$curlopt" --digest --user "$facc" "$furl" -o "$fdst"
+	  else
          curl "$curlopt" "$fsrc" -o "$fdst"
-      fi
+	  fi
    else
       printf "File $dstfn, Size $((fsize/1024))KB, Downloading in $nparts parts ... ...\n\n"
-      if [ -n "$facc" ]; then
-         for (( c=1; c<="$nparts"; c++ )); do
-                local from="$(ecalc "$fsize*($c-1)/$nparts")"
-                if [ "$c" != "$nparts" ]; then
-                    local to="$(ecalc "($fsize*$c/$nparts)-1")"
-                else
-                    local to="$(ecalc "$fsize*$c/$nparts")"
-                fi
-                local fout="$fdst.part$c"
-                ##echo " Starting download thread #$c " >&2
-                printf "\033[A"
-                curl "$curlopt" --digest --user "$facc" --range "$from-$to" "$furl" -o "$fout" &
-         done
-         waiton "$(getpid curl)"
-         printf "\nCombining downloaded parts ... ...\n"
-         for (( c=1; c<="$nparts"; c++ )); do
-            if [ -f "$fdst.part$c" ];then
-               cat "$fdst.part$c" >> "$fdst"
-               \rm -f "$fdst.part$c"
-            else
-               echo "$fdst.part$c is missing."  >&2
-               break
-               return 1
-            fi
-         done
-      else
-         for (( c=1; c<="$nparts"; c++ )); do
-                local from="$(ecalc "$fsize*($c-1)/$nparts")"
-                if [ "$c" != "$nparts" ]; then
-                    local to="$(ecalc "($fsize*$c/$nparts)-1")"
-                else
-                    local to="$(ecalc "$fsize*$c/$nparts")"
-                fi
-                local fout="$fdst.part$c"
-                ##echo " Starting download thread #$c " >&2
-                printf "\033[A"
-                curl "$curlopt" --range "$from-$to" "$furl" -o "$fout" &
-         done
-         waiton "$(getpid curl)"
-         printf "\nCombining downloaded parts ... ...\n"
-         for (( c=1; c<="$nparts"; c++ )); do
-            if [ -f "$fdst.part$c" ];then
-               cat "$fdst.part$c" >> "$fdst"
-               \rm -f "$fdst.part$c"
-            else
-               echo "$fdst.part$c is missing." >&2
-               break
-               return 1
-            fi
-         done
-      fi
+	  if [ -n "$facc" ]; then
+	     for (( c=1; c<="$nparts"; c++ )); do
+				local from="$(ecalc "$fsize*($c-1)/$nparts")"
+				if [ "$c" != "$nparts" ]; then
+					local to="$(ecalc "($fsize*$c/$nparts)-1")"
+				else
+					local to="$(ecalc "$fsize*$c/$nparts")"
+				fi
+				local fout="$fdst.part$c"
+				##echo " Starting download thread #$c " >&2
+				printf "\033[A"
+				curl "$curlopt" --digest --user "$facc" --range "$from-$to" "$furl" -o "$fout" &
+		 done
+		 waiton "$(getpid curl)"
+		 printf "\nCombining downloaded parts ... ...\n"
+		 for (( c=1; c<="$nparts"; c++ )); do
+		    if [ -f "$fdst.part$c" ];then
+			   cat "$fdst.part$c" >> "$fdst"
+			   \rm -f "$fdst.part$c"
+			else
+			   echo "$fdst.part$c is missing."  >&2
+			   break
+			   return 1
+			fi
+		 done
+	  else
+	     for (( c=1; c<="$nparts"; c++ )); do
+				local from="$(ecalc "$fsize*($c-1)/$nparts")"
+				if [ "$c" != "$nparts" ]; then
+					local to="$(ecalc "($fsize*$c/$nparts)-1")"
+				else
+					local to="$(ecalc "$fsize*$c/$nparts")"
+				fi
+				local fout="$fdst.part$c"
+				##echo " Starting download thread #$c " >&2
+				printf "\033[A"
+				curl "$curlopt" --range "$from-$to" "$furl" -o "$fout" &
+		 done
+		 waiton "$(getpid curl)"
+		 printf "\nCombining downloaded parts ... ...\n"
+		 for (( c=1; c<="$nparts"; c++ )); do
+		    if [ -f "$fdst.part$c" ];then
+			   cat "$fdst.part$c" >> "$fdst"
+			   \rm -f "$fdst.part$c"
+			else
+			   echo "$fdst.part$c is missing." >&2
+			   break
+			   return 1
+			fi
+		 done
+	  fi
    fi
    printf "\nMultipart Download complete!\n"
    return 0
diff --git a/shbin/ugetloc b/shbin/ugetloc
--- a/shbin/ugetloc
+++ b/shbin/ugetloc
@@ -1,62 +1,62 @@
 
+## require shbin/abspath, shbin/urifilename
 #---  FUNCTION  -------------------------------------------------------------------------------------------------------
 #          NAME:  ugetloc
 #%   DESCRIPTION:  Curl/fetch down a remote tar ball, extract it and return the script dir location
-#%   USAGE: ugetloc srcurl anchorfile
-#%   REQUIRES: abspath, urifilename, mktemp, curl, [wget], dirname
+#%	 Usage: ugetloc srcurl anchorfile
 #----------------------------------------------------------------------------------------------------------------------
 __ScriptTmp="$(mktemp -d)"
 _ugetloc() {
   ## ugetloc srcurl scriptname
   if [ $# -lt 1 ]; then
-     echo "Usage: ugetloc srcurl anchorfile"
+	 echo "Usage: ugetloc srcurl anchorfile"
      return 1
   else
-     local srcurl="$1"
-     local scriptfile="$2"
+	 local srcurl="$1"
+	 local scriptfile="$2"
   fi
   local urlfile="$(urifile "$srcurl")"
   if [ -z "$urlfile" ]; then
-    echo "No downloadable file is found." >&2
-    return 1
+	echo "No downloadable file is found." >&2
+	return 1
   else
-    scriptfile="${scriptfile:="$urlfile"}"
+	scriptfile="${scriptfile:="$urlfile"}"
   fi
   if iscommand "curl" 2>/dev/null;then
-    curl -L# "$srcurl" -o "$__ScriptTmp/$urlfile" 2>/dev/null
+	curl -L# "$srcurl" -o "$__ScriptTmp/$urlfile" 2>/dev/null
   elif iscommand "wget" 2>/dev/null;then
-    wget -q "$srcurl" -O "$__ScriptTmp/$urlfile" 2>/dev/null
+	wget -q "$srcurl" -O "$__ScriptTmp/$urlfile" 2>/dev/null
   elif iscommand "busybox" 2>/dev/null && [ busybox --list-modules | grep -q wget ];then
-    busybox wget -q "$srcurl" -O "$__ScriptTmp/$urlfile" 2>/dev/null
+	busybox wget -q "$srcurl" -O "$__ScriptTmp/$urlfile" 2>/dev/null
   elif iscommand "fetch" 2>/dev/null;then
-    fetch -q "$srcurl" -o "$__ScriptTmp/$urlfile" 2>/dev/null
+	fetch -q "$srcurl" -o "$__ScriptTmp/$urlfile" 2>/dev/null
   fi
   local dstloc=""
   local hisdir="$(abspath .)"
   cd "$__ScriptTmp" >/dev/null 2>&1
-    case "$urlfile" in
-       *.tar.bz2)   tar xjf "$urlfile"
-                    local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
-                    ;;
-       *.tar.gz)    tar xzf "$urlfile"
-                    local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
-                    ;;
-       *.zip)       unzip "$urlfile"
-                    local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
-                    ;;
-       *.sh | *.py | *.bash | *.*)
-                    local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
-                    ;;
-       *)
-                    local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
-                    ;;
-    esac
-    if [ -f "$realfile" ]; then
-        dstloc="$(dirname $(abspath "$realfile"))"
-    else
-        echo "Cannot find the anchor file [$scriptfile] in downloaded files." >&2
-        return 1
-    fi
+	case "$urlfile" in
+	   *.tar.bz2)   tar xjf "$urlfile"
+					local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
+					;;
+	   *.tar.gz)    tar xzf "$urlfile"
+					local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
+					;;
+	   *.zip)       unzip "$urlfile"
+					local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
+					;;
+	   *.sh | *.py | *.bash | *.*)
+					local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
+					;;
+	   *)
+					local realfile="$(find "$__ScriptTmp" -mindepth 0 -maxdepth 2 -type f -name "$scriptfile")"
+					;;
+	esac
+	if [ -f "$realfile" ]; then
+		dstloc="$(dirname $(abspath "$realfile"))"
+	else
+		echo "Cannot find the anchor file [$scriptfile] in downloaded files." >&2
+		return 1
+	fi
   cd "$hisdir" >/dev/null 2>&1
   echo "$dstloc"
 }
